spring:
  datasource:
    url: jdbc:h2:mem:refillTest
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
      host: localhost
      port: 6379

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: test
    stack:
      auto: false

jwt:
  token:
    secret: "testTesttestTesttestTesttestTesttestTesttestTesttestTesttestTesttestTesttestTesttestTesttestTest"

flask:
  server:
    url: "helloWorld!!!"